# Default values for glueops-cert-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


cert_manager_glueops_specifics:
  captain_domain: nil
  name_of_default_certificate: nil
  aws_accessKey: nil
  aws_region: nil
  aws_secretKey: nil
  

cert-manager:
  webhook:
    hostNetwork: true
    securePort: 10750
    readinessProbe:
      initialDelaySeconds: 120
  crds:
    enabled: true
cert_restore:
  image: nil
  aws_accessKey: nil
  aws_secretKey: nil
  aws_default_region: nil
  captain_domain: nil
  bucket_name: nil
  backup_prefix: nil
  exclude_namespaces: nil
