apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.cert_manager_glueops_specifics.name_of_default_certificate }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  dnsNames:
  - '*.apps.{{ index (index .Values "cert-manager") "captain_domain" }}'
  - '*.{{ index (index .Values "cert-manager") "captain_domain" }}'
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt
  secretName: {{ .Values.cert_manager_glueops_specifics.name_of_default_certificate }}
