apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-nginx-default-certs
spec:
  dnsNames:
  - '*.apps.{{ index (index .Values "cert-manager") "captain_domain" }}'
  - '*.{{ index (index .Values "cert-manager") "captain_domain" }}'
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt
  secretName: ingress-nginx-default-certs
