apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    name: glueops-tls-cert-restore
    namespace: glueops-core-cert-manager
    argocd.argoproj.io/hook: PreSync
spec:
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  suspend: false
  template:
    metadata:
      annotations:
        helm.sh/chart: app-0.4.0
    spec:
      containers:
      - command:
        - python
        - -u
        - /app/cert-backup-restore/main.py
        - --restore
        env:
        - name: AWS_ACCESS_KEY_ID
          value: {{ .Values.cert_restore.aws_accessKey }}
        - name: AWS_SECRET_ACCESS_KEY
          value: {{ .Values.cert_restore.aws_secretKey }}
        - name: AWS_DEFAULT_REGION
          value: {{ .Values.cert_restore.aws_default_region }}
        - name: CAPTAIN_DOMAIN
          value: {{ .Values.cert_restore.captain_domain }}
        - name: BUCKET_NAME
          value: {{ .Values.cert_restore.bucket_name }}
        - name: BACKUP_PREFIX
          value: {{ .Values.cert_restore.backup_prefix }}
        - name: RESTORE_THIS_BACKUP
          value: {{ .Values.cert_restore.restore_this_backup }}
        - name: EXCLUDE_NAMESPACES
          value: {{ .Values.cert_restore.exclude_namespaces }}
        image: {{ .Values.cert_restore.image }}
        imagePullPolicy: IfNotPresent
        name: glueops-tls-cert-restore
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
      nodeSelector:
        glueops.dev/role: glueops-platform
      restartPolicy: Never
      schedulerName: default-scheduler
      serviceAccount: tls-cert-restore
      serviceAccountName: tls-cert-restore
      terminationGracePeriodSeconds: 60
      tolerations:
      - effect: NoSchedule
        key: glueops.dev/role
        operator: Equal
        value: glueops-platform
