apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ index (index .Values "cert-manager") "name_of_default_certificate" }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "1"
spec:
  dnsNames:
  - '*.apps.{{ index (index .Values "cert-manager") "captain_domain" }}'
  - '*.{{ index (index .Values "cert-manager") "captain_domain" }}'
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt
  secretName: {{ index (index .Values "cert-manager") "name_of_default_certificate" }}
