apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: glueops-cert-zerossl-prod
  namespace: glueops-core-cert-manager
spec:
  acme:
    # The ACME server URL
    server: https://acme.zerossl.com/v2/DV90
    externalAccountBinding:
      keyID: {{ index (index .Values "cert-manager") "zerossl_eab_kid" }}
      keySecretRef:
        name: zerossl-eab-hmac-key
        key: secret
      keyAlgorithm: HS256
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: zerossl-prod
       # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: "" # use all ingress classes
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}
