apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tls-cert-restore
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-6"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tls-cert-restore
subjects:
- kind: ServiceAccount
  name: tls-cert-restore
  namespace: glueops-core-cert-manager
