apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-acme-privatekey
    solvers:
    - http01:
        ingress:
          ingressClassName: "public"
    - selector:
        dnsZones:
        - {{ .Values.cert_manager_glueops_specifics.captain_domain }}
      dns01:
        # Valid values are None and Follow
        route53:
          region: {{ .Values.cert_manager_glueops_specifics.aws_region }}
          accessKeyID: {{ .Values.cert_manager_glueops_specifics.aws_accessKey }}
          secretAccessKeySecretRef:
            name: route53-credentials-secret
            key: secret
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  selfSigned: {}
