apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tls-cert-backup
rules:
  - apiGroups:
    - ""
    resources:
    - secrets
    verbs:
    - get
    - list
    - create
    - update
    - patch
  - apiGroups:
    - ""
    resources:
    - namespaces
    verbs:
    - get
    - list
