apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: glueops-cert-zerossl-prod
spec:
  acme:
    # The ACME server URL
    server: https://acme.zerossl.com/v2/DV90
    externalAccountBinding:
      keyID: {{ index (index .Values "cert-manager") "zerossl_eab_kid" }}
      keySecretRef:
        name: zerossl-eab-hmac-key
        key: secret
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: zerossl-prod
       # Enable the HTTP-01 challenge provider
    solvers:
    # - http01:
    #     ingress:
    #       class: "external-ingress-nginx" # use all ingress classes
    - selector:
        dnsZones:
        - '*.glueopshosted.*'
      dns01:
        # Valid values are None and Follow
        route53:
          region: {{ index (index .Values "cert-manager") "aws_region" }}
          accessKeyID: {{ index (index .Values "cert-manager") "aws_accessKey" }}
          secretAccessKeySecretRef:
            name: route53-credentials-secret
            key: secret
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}
