apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: glueops-core-cert-manager
type: Opaque
stringData:
  api-token: {{ index (index .Values "cert-manager") "cloudflare_api_token" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: zerossl-eab-hmac-key
  namespace: glueops-core-cert-manager
stringData:
  secret: {{ index (index .Values "cert-manager") "zerossl_eab_hmac_key" }}
