apiVersion: v1
kind: Secret
metadata:
  name: zerossl-eab-hmac-key
stringData:
  secret: {{ index (index .Values "cert-manager") "zerossl_eab_hmac_key" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: route53-credentials-secret
stringData:
  secret: {{ index (index .Values "cert-manager") "aws_secretKey" }}