name: Update Docs
on:
  push:


jobs:
  call-workflow-passing-data:
    uses: GlueOps/github-workflows/.github/workflows/helm-docs.yml@7b077a4cf0bfbd34eaf0a5f54e4eccedade51606 # main
    secrets: inherit
    
